steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'docker/agent/Dockerfile', '-t', 'gcr.io/virtual-gcp/bigquery-mcp-agent', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/virtual-gcp/bigquery-mcp-agent']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'docker/mcp-toolbox/Dockerfile', '-t', 'gcr.io/virtual-gcp/bigquery-mcp-toolbox', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/virtual-gcp/bigquery-mcp-toolbox']
